-- AlterTable
ALTER TABLE "CAPS_Application_Details" ALTER COLUMN "Date_of_Request" SET DATA TYPE DECIMAL(65,30),
ALTER COLUMN "ReportTime" SET DATA TYPE DECIMAL(65,30),
ALTER COLUMN "ReportNumber" SET DATA TYPE DECIMAL(65,30),
ALTER COLUMN "Enquiry_Reason" SET DATA TYPE DECIMAL(65,30),
ALTER COLUMN "Finance_Purpose" SET DATA TYPE DECIMAL(65,30),
ALTER COLUMN "Amount_Financed" SET DATA TYPE DECIMAL(65,30),
ALTER COLUMN "Duration_Of_Agreement" SET DATA TYPE DECIMAL(65,30);
